name: Deploy to AKS

on:
  push:
    branches:
      - main


jobs:
    Build_Image:
        name: "Build Docker Image"
        runs-on: ubuntu-latest

        steps:
        #Hard code checking out main branch for now
        - name: Checkout Repo
          uses: actions/checkout@v3
          
        - name: Configure Azure
          uses: azure/login@v1
          with:
            client-id: ${{ inputs.CLIENT_ID }}
            tenant-id: ${{ inputs.TENANT_ID }}
            subscription-id: ${{ inputs.SUBSCRIPTION_ID }}
        
        - name: Docker Build
          run: |
            cd dockerfile
            az acr login --name tatatechcr
            az acr build --image tatatechimage --registry tatatechcr -f dockerfile .
        - name: Print Image Name
          run: |
            echo "The image pushed to ACR is backend-image:tatatechimage

    Deploy_Image:
        name: "Deploy Docker Image"
        runs-on: ubuntu-latest

        environment:
            name: main

        steps:

        - name: Configure Azure
          uses: azure/login@v1
          with:
            client-id: ${{ vars.CLIENT_ID }}
            tenant-id: ${{ vars.TENANT_ID }}
            subscription-id: ${{ vars.SUBSCRIPTION_ID }}

        - name: Restarting Web App 
          run: |
            echo "Restarting container to pull latest image in ACR"
            az webapp restart --name containermane --subscription ${{ vars.SUBSCRIPTION_ID }} --resource-group resoursegroupname

        
